# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"
variables:
  - group: KeyVault_group

steps:
  - script: |
      python -m pip install --upgrade pip
    displayName: "install pip"

  - script: |
      pip install -r dev_requirements.txt
    displayName: "install dependencies"

  - script: |
      python ./data_drift/data_drift_main.py \
    displayName: "trigger data drift pipeline"
    env:
      AZURE_TENANT_ID: $(Tenant_ID)
      AML_WORKSPACE_NAME: $(AzureML_Workspace_Name)
      RESOURCE_GROUP: $(Resource_Group)
      SUBSCRIPTION_ID: $(Subscription_ID)
      AZURE_CLIENT_ID: $(Azure_Client_ID)
      AZURE_CLIENT_SECRET: $(Azure_Client_Secret)
      AZURE_LOG_HANDLER_CONNECTION_STRING: $(AZURE_LOG_HANDLER_CONNECTION_STRING)

  - script: |
      python ./model_performance/model_performance_main.py \
    displayName: "trigger model performance pipeline"
    env:
      AZURE_TENANT_ID: $(Tenant_ID)
      AML_WORKSPACE_NAME: $(AzureML_Workspace_Name)
      RESOURCE_GROUP: $(Resource_Group)
      SUBSCRIPTION_ID: $(Subscription_ID)
      AZURE_CLIENT_ID: $(Azure_Client_ID)
      AZURE_CLIENT_SECRET: $(Azure_Client_Secret)
      AZURE_LOG_HANDLER_CONNECTION_STRING: $(AZURE_LOG_HANDLER_CONNECTION_STRING)
